/**
SQL Setup Queries - Generate helper tables specific to Pinellas data.

sqlite3 pinellas_indexed.sqlite < sql/setup.sql

*/

-- Create a "Residences" table using Property Usage codes to exclude hospitals, hotels, timeshares, etc
DROP TABLE IF EXISTS Residences;
CREATE TABLE Residences AS SELECT STRAP as property FROM RP_PROPERTY_INFO
  WHERE PROPERTY_USE REGEXP '0110|0430|0310|0820|0436|0261|0311|0431|0810|7456|0822|0437|0260|0550|0262|1738|0830|2814|4148|1227|8414|0752';

-- Expand the property tax table to better identify and calculate tax categories
DROP VIEW IF EXISTS MillageCategories;
CREATE VIEW MillageCategories AS 
WITH AUTH_SOURCE AS (
  SELECT *,
  CASE
    -- PINELLAS COUNTY SCHOOL BOARD, SCHOOL LOCAL
    WHEN TAX_AUTHORITY IN ('12A', '12B') THEN 'SCHL'
    -- GENERAL FUND, HEALTH DEPARTMENT, PINELLAS COUNTY SCHOOL BOARD, SCHOOL LOCAL, EMERGENCY MEDICAL SERVICE,
    -- PINELLAS PLANNING COUNCIL, JUVENILE WELFARE BOARD, SW FLORIDA WATER MANAGEMENT, SUNCOAST TRANSIT AUTHORITY
    WHEN TAX_AUTHORITY IN ('10A', '10C', '16', '17A', '17B', '17C', '13') THEN 'CNTY'
    ELSE 'MUNI'
  END AS TAX_CATEGORY
  FROM RP_MILLAGE_RATES
)
SELECT *,
  CASE WHEN TAX_CATEGORY = 'SCHL' THEN TAX_RATE_CALC ELSE 0 END AS SCHL_TAX_RATE,
  CASE WHEN TAX_CATEGORY = 'MUNI' THEN TAX_RATE_CALC ELSE 0 END AS MUNI_TAX_RATE,
  CASE WHEN TAX_CATEGORY = 'CNTY' THEN TAX_RATE_CALC ELSE 0 END AS CNTY_TAX_RATE
FROM AUTH_SOURCE
;

-- Calculate 2027 and 2028 Adjusted Taxable Values
DROP TABLE IF EXISTS "PROP_3";
CREATE TABLE "PROP_3" AS 
WITH YR_VALUES AS (
  SELECT
    PI.STRAP as property,
    TAX_DISTRICT,
    CNTY_TAXABLE_VALUE,
    SCHL_TAXABLE_VALUE,
    MUNI_TAXABLE_VALUE,
    TOTAL_LIVING_UNITS as units,
    HX_YN as homestead,
    CASE
      WHEN STR_CITY = '' THEN '?'
      WHEN STR_CITY = 'ST. PETERSBURG' THEN 'ST PETERSBURG'
      ELSE STR_CITY
    END AS city,
    -- CNTY and MUNI Taxable Values
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL 
      THEN MAX(MIN(CNTY_TAXABLE_VALUE + 51411, CNTY_ASD_VALUE) - 150000, 0)
      ELSE CNTY_TAXABLE_VALUE 
    END AS CNTY_TAXABLE_VALUE_2027,
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL 
      THEN MAX(MIN(CNTY_TAXABLE_VALUE + 51411, CNTY_ASD_VALUE) - 250000, 0) 
      ELSE CNTY_TAXABLE_VALUE
    END AS CNTY_TAXABLE_VALUE_2028,
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL 
      THEN MAX(MIN(MUNI_TAXABLE_VALUE + 51411, CNTY_ASD_VALUE) - 150000, 0) 
      ELSE MUNI_TAXABLE_VALUE
    END AS MUNI_TAXABLE_VALUE_2027,
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL 
      THEN MAX(MIN(MUNI_TAXABLE_VALUE + 51411, CNTY_ASD_VALUE) - 250000, 0) 
      ELSE MUNI_TAXABLE_VALUE
    END AS MUNI_TAXABLE_VALUE_2028
  FROM RP_PROPERTY_INFO as PI
    INNER JOIN RP_EXEMPTIONS AS EX ON PI.STRAP = EX.STRAP AND EX.HX_YR = '2026'
    LEFT JOIN Residences AS RE ON RE.Property = PI.STRAP
  WHERE TOTAL_LIVING_UNITS > 0
  AND PI.STRAP NOT IN (
    251025, -- no city
    302833  -- no city
  )
), MILLAGES AS (
  SELECT 
    MILL_CD,
    SUM(CNTY_TAX_RATE) as CNTY_TAX_RATE,
    SUM(SCHL_TAX_RATE) as SCHL_TAX_RATE,
    SUM(MUNI_TAX_RATE) as MUNI_TAX_RATE
  FROM MillageCategories
  GROUP BY 1
), YR_TAXES AS (
  SELECT
    property,
    TAX_DISTRICT,
    CNTY_TAXABLE_VALUE,
    CNTY_TAXABLE_VALUE_2027,
    CNTY_TAXABLE_VALUE_2028,
    SCHL_TAXABLE_VALUE,
    MUNI_TAXABLE_VALUE,
    MUNI_TAXABLE_VALUE_2027,
    MUNI_TAXABLE_VALUE_2028,
    units,
    homestead,
    city,
    CNTY_TAXABLE_VALUE * CNTY_TAX_RATE AS CNTY_TAX_2026,
    CNTY_TAXABLE_VALUE_2027 * CNTY_TAX_RATE AS CNTY_TAX_2027,
    CNTY_TAXABLE_VALUE_2028 * CNTY_TAX_RATE AS CNTY_TAX_2028,
    SCHL_TAXABLE_VALUE * SCHL_TAX_RATE AS SCHL_TAX_2026,
    SCHL_TAXABLE_VALUE * SCHL_TAX_RATE AS SCHL_TAX_2027,
    SCHL_TAXABLE_VALUE * SCHL_TAX_RATE AS SCHL_TAX_2028,
    MUNI_TAXABLE_VALUE * MUNI_TAX_RATE AS MUNI_TAX_2026,
    MUNI_TAXABLE_VALUE_2027 * MUNI_TAX_RATE AS MUNI_TAX_2027,
    MUNI_TAXABLE_VALUE_2028 * MUNI_TAX_RATE AS MUNI_TAX_2028
  FROM YR_VALUES AS YV
    INNER JOIN MILLAGES AS MC ON MC.MILL_CD = YV.TAX_DISTRICT
)
SELECT 
  P.*,
  CNTY_TAX_2026 + SCHL_TAX_2026 + MUNI_TAX_2026 AS TAX_2026,
  CNTY_TAX_2027 + SCHL_TAX_2027 + MUNI_TAX_2027 AS TAX_2027,
  CNTY_TAX_2028 + SCHL_TAX_2028 + MUNI_TAX_2028 AS TAX_2028
FROM YR_TAXES AS P