/**
SQL Setup Queries - Generate helper tables specific to Pinellas data.

sqlite3 pinellas_indexed.sqlite < sql/setup.sql

*/

-- Create a "Residences" table using Property Usage codes to exclude hospitals, hotels, timeshares, etc
DROP TABLE IF EXISTS Residences;
CREATE TABLE Residences AS SELECT STRAP as property FROM RP_PROPERTY_INFO
  WHERE PROPERTY_USE REGEXP '0110|0430|0310|0820|0436|0261|0311|0431|0810|7456|0822|0437|0260|0550|0262|1738|0830|2814|4148|1227|8414|0752';

-- Expand the property tax table to better identify and calculate tax categories
DROP VIEW IF EXISTS MillageCategories;
CREATE VIEW MillageCategories AS SELECT *, 
  CASE
    WHEN TAX_AUTH_NAME LIKE '%SCHOOL%' THEN 'SCHOOL'
    WHEN TAX_AUTH_NAME LIKE '%MUNICIPAL%' THEN 'MUNICIPAL'
    ELSE ''
  END AS TAX_CATEGORY,
  CASE WHEN TAX_AUTH_NAME LIKE '%SCHOOL%' THEN TAX_RATE_CALC ELSE 0 END AS SCHL_TAX_RATE,
  CASE WHEN TAX_AUTH_NAME LIKE '%MUNICIPAL%' THEN TAX_RATE_CALC ELSE 0 END AS MUNI_TAX_RATE,
  CASE WHEN TAX_AUTH_NAME NOT LIKE '%SCHOOL%' AND TAX_AUTH_NAME NOT LIKE '%MUNICIPAL%' THEN TAX_RATE_CALC ELSE 0 END AS CNTY_TAX_RATE
FROM RP_MILLAGE_RATES;

-- Calculate 2027 and 2028 Adjusted Taxable Values
DROP TABLE IF EXISTS "PROP_3";
CREATE TABLE "PROP_3" AS WITH YR_VALUES AS (
  SELECT
    PI.STRAP as property,
    TAX_DISTRICT,
    CNTY_TAXABLE_VALUE,
    SCHL_TAXABLE_VALUE,
    TOTAL_LIVING_UNITS as units,
    HX_YN as homestead,
    CASE
      WHEN STR_CITY = "" THEN "?"
      WHEN STR_CITY = "ST. PETERSBURG" THEN "ST PETERSBURG"
      ELSE STR_CITY END AS city,
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL THEN MAX(CNTY_ASD_VALUE - 150000, 0) ELSE CNTY_TAXABLE_VALUE END AS CNTY_TAXABLE_VALUE_2027,
    CASE WHEN HX_YN = 'Yes' AND RE.Property NOT NULL THEN MAX(CNTY_ASD_VALUE - 250000, 0) ELSE CNTY_TAXABLE_VALUE END AS CNTY_TAXABLE_VALUE_2028
  FROM RP_PROPERTY_INFO as PI
    INNER JOIN RP_EXEMPTIONS AS EX ON PI.STRAP = EX.STRAP AND EX.HX_YR = '2026'
    LEFT JOIN Residences AS RE ON RE.Property = PI.STRAP
  WHERE TOTAL_LIVING_UNITS > 0
  AND PI.STRAP NOT IN (
    650035, -- 0 tax listing, so 2027 calculated tax unexpectedly increases
    251025, -- no city
    302833  -- no city

  )
)
SELECT 
  property, 
  TAX_DISTRICT,
  CNTY_TAXABLE_VALUE,
  SCHL_TAXABLE_VALUE,
  units,
  homestead,
  city,
  CNTY_TAXABLE_VALUE_2027,
  CNTY_TAXABLE_VALUE_2028,
  SUM(
    CNTY_TAXABLE_VALUE * CNTY_TAX_RATE + SCHL_TAXABLE_VALUE * SCHL_TAX_RATE + CNTY_TAXABLE_VALUE * MUNI_TAX_RATE
  ) AS TAX_2026,
  SUM(
    CNTY_TAXABLE_VALUE_2027 * CNTY_TAX_RATE + SCHL_TAXABLE_VALUE * SCHL_TAX_RATE + CNTY_TAXABLE_VALUE_2027 * MUNI_TAX_RATE
  ) AS TAX_2027,
  SUM(
    CNTY_TAXABLE_VALUE_2028 * CNTY_TAX_RATE + SCHL_TAXABLE_VALUE * SCHL_TAX_RATE + CNTY_TAXABLE_VALUE_2027 * MUNI_TAX_RATE
  ) AS TAX_2028
FROM YR_VALUES AS YV
  INNER JOIN MillageCategories AS MC ON MC.MILL_CD = YV.TAX_DISTRICT
GROUP BY 1,2,3,4,5,6,7,8,9;